### ISSUE TITLE
Creating Bookmark Crashes...

### ISSUE THREAD

**Issue by AYT04** [h-lunah/OpenTwitter#9]
It appears that an issue occurs when attempting to create a bookmark. Specifically, the site closes immediately after clicking the bookmark button, suggesting that the application may have crashed, resulting in the tab being closed.

**Comment by celunah** [comment]
I tried to add a bookmark and I cannot reproduce the issue.

It works as intended.

**Comment by AYT04** [comment]
> I tried to add a bookmark and I cannot reproduce the issue.
> 
> It works as intended.

I tried this on my iPhone to see if it’s just a desktop issue and it does in fact close the page the website after I bookmark but when I go back to the bookmark, it shows up..

**Comment by celunah** [comment]
I still can't reproduce. I tried bookmarking on iPhone, and it works.
